from groq import Groq
from src.config import GROQ_API_KEY
import json

class CareerReportGenerator:
    """
    Generate AI-powered career reports and recommendations.😊
    """

    def __init__(self):
        self.client = Groq(api_key=GROQ_API_KEY)

    def build_prompt(self, career_report):
        """
        Builds a structured prompt for the LLM using the
        output generated by CareerAdvisor.

        Parameters
        ----------
        career_report : dict
            Dictionary returned by CareerAdvisor.

        Returns
        -------
        str
            Prompt to send to the LLM.
        """

        match_score = career_report["match_score"]

        best_roles = career_report["best_roles"]

        strengths = career_report["strengths"]

        missing_skills = career_report["missing_skills"]

        recommendations = career_report["recommendations"]


        prompt = f"""
    You are an experienced Software Engineering Career Coach.

    You are analyzing a candidate based ONLY on the information provided below.

    Do NOT invent skills.
    Do NOT invent experience.
    Do NOT assume anything not mentioned.

    ==============================
    Candidate Analysis
    ==============================

    Overall Match Score:
    {match_score}%

    Recommended Career Paths:
    {chr(10).join("- " + role for role in best_roles)}

    Candidate Strengths:
    {chr(10).join("- " + strength for strength in strengths)}

    Missing Skills:
    {chr(10).join("- " + skill for skill in missing_skills)}

    Existing Recommendations:
    {chr(10).join("- " + rec for rec in recommendations)}

    ==============================
    Task
    ==============================

    Using ONLY the information provided above, generate a personalized career report.

    Return your response as a VALID JSON object.

    Do not include markdown.

    Do not wrap the JSON inside triple backticks.

    Do not add explanations before or after the JSON.

    Use the following JSON schema exactly:

    {{
        "career_summary": "...",

        "career_path_explanation": "...",

        "strength_analysis": "...",

        "skill_gap_analysis": "...",

        "learning_roadmap": [
            "...",
            "...",
            "...",
            "...",
            "..."
        ],

        "motivation": "..."
    }}

    Requirements:

    - Use only the supplied information.
    - Do not invent skills or experience.
    - Explain why the recommended career paths fit the candidate.
    - Explain why the missing skills are important.
    - Suggest a logical learning order for the roadmap.
    - Keep the tone professional, encouraging and realistic.
    - The total response should be approximately 500–700 words.
    """

        return prompt
    
    def generate_report(self, career_report):
        """
        Generates a personalized AI career report.

        Parameters
        ----------
        career_report : dict
            Structured report generated by CareerAdvisor.

        Returns
        -------
        str
            AI-generated career report.
        """

        prompt = self.build_prompt(career_report)

        response = self.client.chat.completions.create(
            model="llama-3.3-70b-versatile",

            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are an expert software engineering career coach."
                    )
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ],

            temperature=0.5,

            max_tokens=1200
        )

        content = response.choices[0].message.content
        return self.clean_response(content)
    
    def clean_response(self, response):
        """
        Cleans the LLM response and converts it into
        a Python dictionary.

        Parameters
        ----------
        response : str
            Raw response returned by the LLM.

        Returns
        -------
        dict
            Parsed JSON response.
        """

        response = response.strip()

        if response.startswith("```json"):
            response = response.replace("```json", "", 1)

        if response.startswith("```"):
            response = response.replace("```", "", 1)

        if response.endswith("```"):
            response = response[:-3]

        response = response.strip()

        return json.loads(response)