function MatchScoreCard({ score }) {

    const getStatus = () => {

        if (score >= 80) return "Excellent Match";
        if (score >= 60) return "Good Match";

        return "Needs Improvement";
    };

    return (

        <section id="match-score" className="mt-8 rounded-3xl bg-white p-8 shadow-md">

            <h2 className="text-2xl font-bold text-slate-900">

                🎯 Overall Match Score

            </h2>

            <div className="mt-8">

                <h1 className="text-6xl font-bold text-blue-600">

                    {score}%

                </h1>

                <p className="mt-2 text-lg font-medium text-slate-700">

                    {getStatus()}

                </p>

            </div>

            {/* Progress Bar */}

            <div className="mt-8 h-3 w-full overflow-hidden rounded-full bg-slate-200">

                <div

                    className="h-full rounded-full bg-blue-600 transition-all duration-500"

                    style={{

                        width: `${score}%`

                    }}

                />

            </div>

            <p className="mt-6 text-slate-600 leading-7">

                Based on your uploaded resume, your profile shows
                a strong alignment with the recommended career
                opportunities generated by our AI system.

            </p>

        </section>

    );

}

export default MatchScoreCard;