import { Map, CheckCircle2 } from "lucide-react";

function RoadmapCard({ roadmap }) {

    return (

        <section
            id="learning-roadmap"
            className="mt-8 rounded-3xl bg-white p-8 shadow-md"
        >

            {/* Header */}

            <div className="flex items-center gap-3">

                <Map
                    size={30}
                    className="text-blue-600"
                />

                <div>

                    <h2 className="text-2xl font-bold text-slate-900">

                        Learning Roadmap

                    </h2>

                    <p className="mt-1 text-slate-600">

                        A personalized roadmap generated by our AI to help you improve your career prospects.

                    </p>

                </div>

            </div>

            {/* Roadmap */}

            <div className="mt-10 space-y-6">

                {

                    roadmap.map((step, index) => (

                        <div
                            key={index}
                            className="flex gap-5"
                        >

                            {/* Step Number */}

                            <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-blue-600 font-bold text-white">

                                {index + 1}

                            </div>

                            {/* Step Content */}

                            <div className="flex-1 rounded-2xl border border-slate-200 bg-slate-50 p-5">

                                <div className="flex items-center gap-2">

                                    <CheckCircle2
                                        size={18}
                                        className="text-green-600"
                                    />

                                    <h3 className="font-semibold text-slate-900">

                                        Step {index + 1}

                                    </h3>

                                </div>

                                <p className="mt-3 leading-7 text-slate-700">

                                    {step}

                                </p>

                            </div>

                        </div>

                    ))

                }

            </div>

        </section>

    );

}

export default RoadmapCard;